### ISSUE TITLE
AutoHotkey download is now located at ahkscript.org

### ISSUE THREAD

**Issue by G33kDude** [fabd/rift-mouselook-addon#1]
The latest AutoHotkey downloads are at http://ahkscript.org/. AutoHotkey.com gives a download for a really old version of AutoHotkey

**Comment by fabd** [comment]
Thanks. The link was corrected in the Oct 31, 2014 commit after someone emailed me about an issue that was related to the old Autohotkey. I don't see any other links.

**Comment by fabd** [comment]
Thanks, I see that there was an old link in the README.txt file. Committed the updated link.
